# Tests for releases and release candidates
#
# Runs on every tag creation, and all pushes and PRs to release branches
# named "v1.2.x", etc.
#
# This workflow is more extensive than the regular test workflow.
# - Tests are executed on more Python versions
# - Tests are run on more operating systems
# - N.B. There is no pip cache here to ensure runs are always against the
#   very latest versions of dependencies, even if this workflow ran recently.
#
# In addition, the package is built as a wheel on each OS/Python job, and these
# are stored as artifacts to use for your distribution process. There is an
# extra job (disabled by default) which can be enabled to push to Test PyPI.

name: release candidate tests

on:
  push:
    branches:
      # Release branches.
      # Examples: "v1", "v3.0", "v1.2.x", "1.5.0", "1.2rc0"
      # Expected usage is (for example) a branch named "v1.2.x" which contains
      # the latest release in the 1.2 series.
      - 'v[0-9]+'
      - 'v?[0-9]+.[0-9x]+'
      - 'v?[0-9]+.[0-9]+.[0-9x]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+.[0-9x]+'
      - 'v?[0-9]+.[0-9x]+rc[0-9]*'
    tags:
      # Run whenever any tag is created
      - '**'
  pull_request:
    branches:
      # Release branches
      - 'v[0-9]+'
      - 'v?[0-9]+.[0-9x]+'
      - 'v?[0-9]+.[0-9]+.[0-9x]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+.[0-9x]+'
      - 'v?[0-9]+.[0-9x]+rc[0-9]*'
  release:
    # Run on a new release
    types: [created, edited, published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download wheel artifacts
      uses: actions/download-artifact@v2
      with:
        name: wheel-*
        path: dist/

    - name: Store aggregated wheel artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist/*

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags/')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
